# Generated by Django 2.0.6 on 2018-06-16 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hknweb', '0003_auto_20180406_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
